/* Generated By:JavaCC: Do not edit this line. analizadorExpresionTreeConstants.java Version 6.0_1 */
package Expresion;

public interface analizadorExpresionTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTEXPRESION = 2;
  public int JJTCONDICION = 3;
  public int JJTVOID = 4;
  public int JJTOR = 5;
  public int JJTAND = 6;
  public int JJTNUVA_CONDICIONNOT = 7;
  public int JJTNUVA_CONDICION = 8;
  public int JJTOPERADOR = 9;
  public int JJTSUMA = 10;
  public int JJTRESTA = 11;
  public int JJTMULTIPLICACION = 12;
  public int JJTDIVISION = 13;
  public int JJTPOTENCIA = 14;
  public int JJTHORA = 15;
  public int JJTFECHAHORA = 16;
  public int JJTFECHA_HORA = 17;
  public int JJTFECHA = 18;
  public int JJTCADENA = 19;
  public int JJTENTERO = 20;
  public int JJTDECIMAL = 21;
  public int JJTBOOLEANO = 22;
  public int JJTBOOL = 23;
  public int JJTNULO = 24;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "EXPRESION",
    "Condicion",
    "void",
    "Or",
    "And",
    "Nuva_CondicionNOT",
    "Nuva_Condicion",
    "Operador",
    "Suma",
    "Resta",
    "Multiplicacion",
    "Division",
    "Potencia",
    "Hora",
    "FechaHora",
    "FECHA_HORA",
    "Fecha",
    "Cadena",
    "Entero",
    "DECIMAL",
    "Booleano",
    "BOOL",
    "Nulo",
  };
}
/* JavaCC - OriginalChecksum=f39654f6892a12ab028fcd383eafd7d7 (do not edit this line) */
