/* Generated By:JJTree&JavaCC: Do not edit this line. analizadorExpresionConstants.java */
package Expresion;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface analizadorExpresionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int menos_menos = 15;
  /** RegularExpression Id. */
  int mas_mas = 16;
  /** RegularExpression Id. */
  int S_MAS = 17;
  /** RegularExpression Id. */
  int S_MENOS = 18;
  /** RegularExpression Id. */
  int S_POR = 19;
  /** RegularExpression Id. */
  int S_DIV = 20;
  /** RegularExpression Id. */
  int S_POT = 21;
  /** RegularExpression Id. */
  int S_MOD = 22;
  /** RegularExpression Id. */
  int VERDADERO = 23;
  /** RegularExpression Id. */
  int FALSO = 24;
  /** RegularExpression Id. */
  int NULO = 25;
  /** RegularExpression Id. */
  int abre_par = 26;
  /** RegularExpression Id. */
  int cierra_par = 27;
  /** RegularExpression Id. */
  int coma = 28;
  /** RegularExpression Id. */
  int dos_puntos = 29;
  /** RegularExpression Id. */
  int punto = 30;
  /** RegularExpression Id. */
  int COMILLA_SIMPLE = 31;
  /** RegularExpression Id. */
  int COMILLA_DOBLE = 32;
  /** RegularExpression Id. */
  int DECIMAL = 33;
  /** RegularExpression Id. */
  int NUM = 34;
  /** RegularExpression Id. */
  int fechaS = 35;
  /** RegularExpression Id. */
  int horaS = 36;
  /** RegularExpression Id. */
  int fechaHoraS = 37;
  /** RegularExpression Id. */
  int CADENA = 38;
  /** RegularExpression Id. */
  int CARACTER = 39;
  /** RegularExpression Id. */
  int id = 40;
  /** RegularExpression Id. */
  int LETRA = 41;
  /** RegularExpression Id. */
  int DIGITO = 42;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;
  /** Lexical state. */
  int COMMENT2 = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"#*\"",
    "\"\\n\"",
    "\"#\"",
    "\"*#\"",
    "<token of kind 9>",
    "\"\\n\"",
    "<token of kind 11>",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"--\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"%\"",
    "\"verdadero\"",
    "\"falso\"",
    "\"nulo\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
    "\".\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<DECIMAL>",
    "<NUM>",
    "<fechaS>",
    "<horaS>",
    "<fechaHoraS>",
    "<CADENA>",
    "<CARACTER>",
    "<id>",
    "<LETRA>",
    "<DIGITO>",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
  };

}
