/* Generated By:JavaCC: Do not edit this line. analizadorTreeConstants.java Version 6.0_1 */
package Analizador;

public interface analizadorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTTAG_ABRE = 2;
  public int JJTTAG_CIERRA = 3;
  public int JJTENCABEZADO = 4;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "TAG_ABRE",
    "TAG_CIERRA",
    "Encabezado",
  };
}
/* JavaCC - OriginalChecksum=475907a8c972c2e7b03b216d504ec5ed (do not edit this line) */
