/* Generated By:JJTree&JavaCC: Do not edit this line. grammarXLSXConstants.java */
package XLSX.AnalizerXML;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grammarXLSXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tipoC = 12;
  /** RegularExpression Id. */
  int idPreguntaC = 13;
  /** RegularExpression Id. */
  int etiquetaC = 14;
  /** RegularExpression Id. */
  int sugerirC = 15;
  /** RegularExpression Id. */
  int codigo_preC = 16;
  /** RegularExpression Id. */
  int codigo_postC = 17;
  /** RegularExpression Id. */
  int restringirC = 18;
  /** RegularExpression Id. */
  int restringirMsnC = 19;
  /** RegularExpression Id. */
  int predeterminadoC = 20;
  /** RegularExpression Id. */
  int aplicableC = 21;
  /** RegularExpression Id. */
  int lecturaC = 22;
  /** RegularExpression Id. */
  int calculoC = 23;
  /** RegularExpression Id. */
  int repeticionC = 24;
  /** RegularExpression Id. */
  int multimediaC = 25;
  /** RegularExpression Id. */
  int aparienciaC = 26;
  /** RegularExpression Id. */
  int parametroC = 27;
  /** RegularExpression Id. */
  int tipoC2 = 28;
  /** RegularExpression Id. */
  int idPreguntaC2 = 29;
  /** RegularExpression Id. */
  int etiquetaC2 = 30;
  /** RegularExpression Id. */
  int sugerirC2 = 31;
  /** RegularExpression Id. */
  int codigo_preC2 = 32;
  /** RegularExpression Id. */
  int codigo_postC2 = 33;
  /** RegularExpression Id. */
  int restringirC2 = 34;
  /** RegularExpression Id. */
  int restringirMsnC2 = 35;
  /** RegularExpression Id. */
  int predeterminadoC2 = 36;
  /** RegularExpression Id. */
  int aplicableC2 = 37;
  /** RegularExpression Id. */
  int lecturaC2 = 38;
  /** RegularExpression Id. */
  int calculoC2 = 39;
  /** RegularExpression Id. */
  int repeticionC2 = 40;
  /** RegularExpression Id. */
  int multimediaC2 = 41;
  /** RegularExpression Id. */
  int aparienciaC2 = 42;
  /** RegularExpression Id. */
  int parametroC2 = 43;
  /** RegularExpression Id. */
  int menorIgual = 44;
  /** RegularExpression Id. */
  int mayorIgual = 45;
  /** RegularExpression Id. */
  int menor = 46;
  /** RegularExpression Id. */
  int mayor = 47;
  /** RegularExpression Id. */
  int igualIgual = 48;
  /** RegularExpression Id. */
  int distintoA = 49;
  /** RegularExpression Id. */
  int or = 50;
  /** RegularExpression Id. */
  int and = 51;
  /** RegularExpression Id. */
  int not = 52;
  /** RegularExpression Id. */
  int menosMenos = 53;
  /** RegularExpression Id. */
  int masMas = 54;
  /** RegularExpression Id. */
  int suma = 55;
  /** RegularExpression Id. */
  int resta = 56;
  /** RegularExpression Id. */
  int multiplicacion = 57;
  /** RegularExpression Id. */
  int division = 58;
  /** RegularExpression Id. */
  int modulo = 59;
  /** RegularExpression Id. */
  int div = 60;
  /** RegularExpression Id. */
  int potencia = 61;
  /** RegularExpression Id. */
  int igual = 62;
  /** RegularExpression Id. */
  int dosPuntos = 63;
  /** RegularExpression Id. */
  int abrePar = 64;
  /** RegularExpression Id. */
  int cierraPar = 65;
  /** RegularExpression Id. */
  int coma = 66;
  /** RegularExpression Id. */
  int doblePunto = 67;
  /** RegularExpression Id. */
  int punto = 68;
  /** RegularExpression Id. */
  int puntoComa = 69;
  /** RegularExpression Id. */
  int abreLlave = 70;
  /** RegularExpression Id. */
  int cierraLlave = 71;
  /** RegularExpression Id. */
  int abreCorchete = 72;
  /** RegularExpression Id. */
  int cierraCorchete = 73;
  /** RegularExpression Id. */
  int arroba = 74;
  /** RegularExpression Id. */
  int DECIMAL = 75;
  /** RegularExpression Id. */
  int NUM = 76;
  /** RegularExpression Id. */
  int CADENA = 77;
  /** RegularExpression Id. */
  int CARACTER = 78;
  /** RegularExpression Id. */
  int id = 79;
  /** RegularExpression Id. */
  int LETRA = 80;
  /** RegularExpression Id. */
  int DIGITO = 81;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;
  /** Lexical state. */
  int COMMENT2 = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"$#\"",
    "\"\\n\"",
    "\"$$\"",
    "\"#$\"",
    "<token of kind 9>",
    "\"\\n\"",
    "<token of kind 11>",
    "\"<tipo>\"",
    "\"<idPregunta>\"",
    "\"<etiqueta>\"",
    "\"<sugerir>\"",
    "\"<codigo_pre>\"",
    "\"<codigo_post>\"",
    "\"<restringir>\"",
    "\"<restringirMsn>\"",
    "\"<predeterminado>\"",
    "\"<aplicable>\"",
    "\"<lectura>\"",
    "\"<calculo>\"",
    "\"<repeticion>\"",
    "\"<multimedia>\"",
    "\"<apariencia>\"",
    "\"<parametro>\"",
    "\"</tipo>\"",
    "\"</idPregunta>\"",
    "\"</etiqueta>\"",
    "\"</sugerir>\"",
    "\"</codigo_pre>\"",
    "\"</codigo_post>\"",
    "\"</restringir>\"",
    "\"</restringirMsn>\"",
    "\"</predeterminado>\"",
    "\"</aplicable>\"",
    "\"</lectura>\"",
    "\"</calculo>\"",
    "\"</repeticion>\"",
    "\"</multimedia>\"",
    "\"</apariencia>\"",
    "\"</parametro>\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"--\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "\"div\"",
    "\"^\"",
    "\"=\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"..\"",
    "\".\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"@\"",
    "<DECIMAL>",
    "<NUM>",
    "<CADENA>",
    "<CARACTER>",
    "<id>",
    "<LETRA>",
    "<DIGITO>",
  };

}
