/* Generated By:JJTree&JavaCC: Do not edit this line. grammarXLSXConstants.java */
package XLSX.AnalizerXML;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grammarXLSXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int etiqueta = 24;
  /** RegularExpression Id. */
  int sugerir = 25;
  /** RegularExpression Id. */
  int codigo_pre = 26;
  /** RegularExpression Id. */
  int codigo_post = 27;
  /** RegularExpression Id. */
  int restringirMsn = 28;
  /** RegularExpression Id. */
  int requeridoMsn = 29;
  /** RegularExpression Id. */
  int predeterminado = 30;
  /** RegularExpression Id. */
  int importar = 31;
  /** RegularExpression Id. */
  int codigo_principal = 32;
  /** RegularExpression Id. */
  int codigo_global = 33;
  /** RegularExpression Id. */
  int titulo_formulario = 34;
  /** RegularExpression Id. */
  int nombre_lista = 35;
  /** RegularExpression Id. */
  int menorIgual_ = 43;
  /** RegularExpression Id. */
  int mayorIgual_ = 44;
  /** RegularExpression Id. */
  int menor_ = 45;
  /** RegularExpression Id. */
  int mayor_ = 46;
  /** RegularExpression Id. */
  int igualIgual_ = 47;
  /** RegularExpression Id. */
  int distintoA_ = 48;
  /** RegularExpression Id. */
  int menosMenos_ = 49;
  /** RegularExpression Id. */
  int masMas_ = 50;
  /** RegularExpression Id. */
  int suma_ = 51;
  /** RegularExpression Id. */
  int resta_ = 52;
  /** RegularExpression Id. */
  int multiplicacion_ = 53;
  /** RegularExpression Id. */
  int modulo_ = 54;
  /** RegularExpression Id. */
  int div_ = 55;
  /** RegularExpression Id. */
  int potencia_ = 56;
  /** RegularExpression Id. */
  int or_ = 57;
  /** RegularExpression Id. */
  int and_ = 58;
  /** RegularExpression Id. */
  int not_ = 59;
  /** RegularExpression Id. */
  int igual_ = 60;
  /** RegularExpression Id. */
  int doblePunto_ = 61;
  /** RegularExpression Id. */
  int punto_ = 62;
  /** RegularExpression Id. */
  int arroba_ = 63;
  /** RegularExpression Id. */
  int abrePar_ = 64;
  /** RegularExpression Id. */
  int cierraPar_ = 65;
  /** RegularExpression Id. */
  int NUM_ = 66;
  /** RegularExpression Id. */
  int CARACTER_ = 67;
  /** RegularExpression Id. */
  int tagid_ = 68;
  /** RegularExpression Id. */
  int id_ = 69;
  /** RegularExpression Id. */
  int CADENA_ = 70;
  /** RegularExpression Id. */
  int NUMERAL_ = 71;
  /** RegularExpression Id. */
  int hexa_ = 72;
  /** RegularExpression Id. */
  int LETRA_ = 73;
  /** RegularExpression Id. */
  int DIGITO_ = 74;
  /** RegularExpression Id. */
  int restringir = 80;
  /** RegularExpression Id. */
  int aplicable = 81;
  /** RegularExpression Id. */
  int calculo = 82;
  /** RegularExpression Id. */
  int repeticion = 83;
  /** RegularExpression Id. */
  int requerido = 84;
  /** RegularExpression Id. */
  int lectura = 85;
  /** RegularExpression Id. */
  int imagen = 86;
  /** RegularExpression Id. */
  int audio = 87;
  /** RegularExpression Id. */
  int video = 88;
  /** RegularExpression Id. */
  int verdadero = 89;
  /** RegularExpression Id. */
  int falso = 90;
  /** RegularExpression Id. */
  int reproduccion = 91;
  /** RegularExpression Id. */
  int cad_min = 92;
  /** RegularExpression Id. */
  int cad_max = 93;
  /** RegularExpression Id. */
  int iniciar = 94;
  /** RegularExpression Id. */
  int finalizar = 95;
  /** RegularExpression Id. */
  int opcion = 96;
  /** RegularExpression Id. */
  int v_f = 97;
  /** RegularExpression Id. */
  int si_no = 98;
  /** RegularExpression Id. */
  int cad_fila = 99;
  /** RegularExpression Id. */
  int pagina = 100;
  /** RegularExpression Id. */
  int todo = 101;
  /** RegularExpression Id. */
  int cuadricula = 102;
  /** RegularExpression Id. */
  int texto = 103;
  /** RegularExpression Id. */
  int entero = 104;
  /** RegularExpression Id. */
  int decimal = 105;
  /** RegularExpression Id. */
  int rango = 106;
  /** RegularExpression Id. */
  int condicion = 107;
  /** RegularExpression Id. */
  int hora = 108;
  /** RegularExpression Id. */
  int fecha = 109;
  /** RegularExpression Id. */
  int fechahora = 110;
  /** RegularExpression Id. */
  int selecciona_uno = 111;
  /** RegularExpression Id. */
  int selecciona_multiples = 112;
  /** RegularExpression Id. */
  int nota = 113;
  /** RegularExpression Id. */
  int fichero = 114;
  /** RegularExpression Id. */
  int calcular = 115;
  /** RegularExpression Id. */
  int ciclo = 116;
  /** RegularExpression Id. */
  int agrupacion = 117;
  /** RegularExpression Id. */
  int opt = 118;
  /** RegularExpression Id. */
  int preg = 119;
  /** RegularExpression Id. */
  int confi = 120;
  /** RegularExpression Id. */
  int opt2 = 121;
  /** RegularExpression Id. */
  int preg2 = 122;
  /** RegularExpression Id. */
  int confi2 = 123;
  /** RegularExpression Id. */
  int nombre = 124;
  /** RegularExpression Id. */
  int multimedia = 125;
  /** RegularExpression Id. */
  int nombre2 = 126;
  /** RegularExpression Id. */
  int etiqueta2 = 127;
  /** RegularExpression Id. */
  int multimedia2 = 128;
  /** RegularExpression Id. */
  int idform = 129;
  /** RegularExpression Id. */
  int estilo = 130;
  /** RegularExpression Id. */
  int idform2 = 131;
  /** RegularExpression Id. */
  int estilo2 = 132;
  /** RegularExpression Id. */
  int encuesta = 133;
  /** RegularExpression Id. */
  int opciones = 134;
  /** RegularExpression Id. */
  int configuraciones = 135;
  /** RegularExpression Id. */
  int encuesta2 = 136;
  /** RegularExpression Id. */
  int opciones2 = 137;
  /** RegularExpression Id. */
  int configuraciones2 = 138;
  /** RegularExpression Id. */
  int tipoC = 139;
  /** RegularExpression Id. */
  int idPreguntaC = 140;
  /** RegularExpression Id. */
  int requeridoMsnC2 = 141;
  /** RegularExpression Id. */
  int aparienciaC = 142;
  /** RegularExpression Id. */
  int parametroC = 143;
  /** RegularExpression Id. */
  int tipoC2 = 144;
  /** RegularExpression Id. */
  int idPreguntaC2 = 145;
  /** RegularExpression Id. */
  int sugerirC2 = 146;
  /** RegularExpression Id. */
  int codigo_preC2 = 147;
  /** RegularExpression Id. */
  int codigo_postC2 = 148;
  /** RegularExpression Id. */
  int restringirC2 = 149;
  /** RegularExpression Id. */
  int restringirMsnC2 = 150;
  /** RegularExpression Id. */
  int predeterminadoC2 = 151;
  /** RegularExpression Id. */
  int aplicableC2 = 152;
  /** RegularExpression Id. */
  int calculoC2 = 153;
  /** RegularExpression Id. */
  int repeticionC2 = 154;
  /** RegularExpression Id. */
  int aparienciaC2 = 155;
  /** RegularExpression Id. */
  int parametroC2 = 156;
  /** RegularExpression Id. */
  int menorIgual = 157;
  /** RegularExpression Id. */
  int mayorIgual = 158;
  /** RegularExpression Id. */
  int menor = 159;
  /** RegularExpression Id. */
  int mayor = 160;
  /** RegularExpression Id. */
  int igualIgual = 161;
  /** RegularExpression Id. */
  int distintoA = 162;
  /** RegularExpression Id. */
  int menosMenos = 163;
  /** RegularExpression Id. */
  int masMas = 164;
  /** RegularExpression Id. */
  int suma = 165;
  /** RegularExpression Id. */
  int resta = 166;
  /** RegularExpression Id. */
  int multiplicacion = 167;
  /** RegularExpression Id. */
  int division = 168;
  /** RegularExpression Id. */
  int modulo = 169;
  /** RegularExpression Id. */
  int div = 170;
  /** RegularExpression Id. */
  int potencia = 171;
  /** RegularExpression Id. */
  int or = 172;
  /** RegularExpression Id. */
  int and = 173;
  /** RegularExpression Id. */
  int not = 174;
  /** RegularExpression Id. */
  int igual = 175;
  /** RegularExpression Id. */
  int doblePunto = 176;
  /** RegularExpression Id. */
  int punto = 177;
  /** RegularExpression Id. */
  int arroba = 178;
  /** RegularExpression Id. */
  int abrePar = 179;
  /** RegularExpression Id. */
  int cierraPar = 180;
  /** RegularExpression Id. */
  int dosPuntos = 181;
  /** RegularExpression Id. */
  int coma = 182;
  /** RegularExpression Id. */
  int puntoComa = 183;
  /** RegularExpression Id. */
  int abreLlave = 184;
  /** RegularExpression Id. */
  int cierraLlave = 185;
  /** RegularExpression Id. */
  int abreCorchete = 186;
  /** RegularExpression Id. */
  int cierraCorchete = 187;
  /** RegularExpression Id. */
  int pregunta1 = 188;
  /** RegularExpression Id. */
  int pregunta2 = 189;
  /** RegularExpression Id. */
  int exclamacion = 190;
  /** RegularExpression Id. */
  int id = 191;
  /** RegularExpression Id. */
  int NUM = 192;
  /** RegularExpression Id. */
  int CARACTER = 193;
  /** RegularExpression Id. */
  int tagid = 194;
  /** RegularExpression Id. */
  int CADENA = 195;
  /** RegularExpression Id. */
  int NUMERAL = 196;
  /** RegularExpression Id. */
  int hexa = 197;
  /** RegularExpression Id. */
  int LETRA = 198;
  /** RegularExpression Id. */
  int DIGITO = 199;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;
  /** Lexical state. */
  int COMMENT2 = 2;
  /** Lexical state. */
  int estado2 = 3;
  /** Lexical state. */
  int operaciones = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"$#\"",
    "\"\\n\"",
    "\"$$\"",
    "\"#$\"",
    "<token of kind 9>",
    "\"\\n\"",
    "<token of kind 11>",
    "\"<etiqueta>\"",
    "\"<sugerir>\"",
    "\"<codigo_pre>\"",
    "\"<codigo_post>\"",
    "\"<restringirMsn>\"",
    "\"<requeridoMsn>\"",
    "\"<predeterminado>\"",
    "\"<importar>\"",
    "\"<codigo_principal>\"",
    "\"<codigo_global>\"",
    "\"<titulo_formulario>\"",
    "\"<nombre_lista>\"",
    "\"</etiqueta>\"",
    "\"</sugerir>\"",
    "\"</codigo_pre>\"",
    "\"</codigo_post>\"",
    "\"</restringirMsn>\"",
    "\"</requeridoMsn>\"",
    "\"</predeterminado>\"",
    "\"</importar>\"",
    "\"</codigo_principal>\"",
    "\"</codigo_global>\"",
    "\"</titulo_formulario>\"",
    "\"</nombre_lista>\"",
    "<token of kind 36>",
    "\"<restringir>\"",
    "\"<aplicable>\"",
    "\"<calculo>\"",
    "\"<repeticion>\"",
    "\"<requerido>\"",
    "\"<lectura>\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"--\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"mod\"",
    "\"div\"",
    "\"^\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"=\"",
    "\"..\"",
    "\".\"",
    "\"@\"",
    "\"(\"",
    "\")\"",
    "<NUM_>",
    "<CARACTER_>",
    "<tagid_>",
    "<id_>",
    "<CADENA_>",
    "<NUMERAL_>",
    "<hexa_>",
    "<LETRA_>",
    "<DIGITO_>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"</restringir>\"",
    "\"</aplicable>\"",
    "\"</calculo>\"",
    "\"</repeticion>\"",
    "\"</requerido>\"",
    "\"</lectura>\"",
    "\"media_imagen\"",
    "\"media_audio\"",
    "\"media_video\"",
    "\"verdadero\"",
    "\"falso\"",
    "\"reproduccion\"",
    "\"cad_min\"",
    "\"cad_max\"",
    "\"iniciar\"",
    "\"finalizar\"",
    "\"opcion\"",
    "\"v_f\"",
    "\"si_no\"",
    "\"cad_fila\"",
    "\"pagina\"",
    "\"todo\"",
    "\"cuadricula\"",
    "\"texto\"",
    "\"entero\"",
    "\"decimal\"",
    "\"rango\"",
    "\"condicion\"",
    "\"hora\"",
    "\"fecha\"",
    "\"fechahora\"",
    "\"selecciona_uno\"",
    "\"selecciona_multiples\"",
    "\"nota\"",
    "\"fichero\"",
    "\"calcular\"",
    "\"ciclo\"",
    "\"agrupacion\"",
    "\"<opt>\"",
    "\"<preg>\"",
    "\"<confi>\"",
    "\"</opt>\"",
    "\"</preg>\"",
    "\"</confi>\"",
    "\"<nombre>\"",
    "\"<multimedia>\"",
    "\"</nombre>\"",
    "\"</etiqueta>\"",
    "\"</multimedia>\"",
    "\"<idForm>\"",
    "\"<estilo>\"",
    "\"</idForm>\"",
    "\"</estilo>\"",
    "\"<encuesta>\"",
    "\"<opciones>\"",
    "\"<configuracion>\"",
    "\"</encuesta>\"",
    "\"</opciones>\"",
    "\"</configuracion>\"",
    "\"<tipo>\"",
    "\"<idPregunta>\"",
    "\"</requeridoMsn>\"",
    "\"<apariencia>\"",
    "\"<parametro>\"",
    "\"</tipo>\"",
    "\"</idPregunta>\"",
    "\"</sugerir>\"",
    "\"</codigo_pre>\"",
    "\"</codigo_post>\"",
    "\"</restringir>\"",
    "\"</restringirMsn>\"",
    "\"</predeterminado>\"",
    "\"</aplicable>\"",
    "\"</calculo>\"",
    "\"</repeticion>\"",
    "\"</apariencia>\"",
    "\"</parametro>\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"--\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "\"div\"",
    "\"^\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"=\"",
    "\"..\"",
    "\".\"",
    "\"@\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"?\"",
    "\"\\u00c2\\u00bf\"",
    "\"\\u00c2\\u00a1\"",
    "<id>",
    "<NUM>",
    "<CARACTER>",
    "<tagid>",
    "<CADENA>",
    "<NUMERAL>",
    "<hexa>",
    "<LETRA>",
    "<DIGITO>",
  };

}
