/* Generated By:JavaCC: Do not edit this line. grammarXLSXTreeConstants.java Version 5.0 */
package XLSX.AnalizerXML;

public interface grammarXLSXTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTTAG = 2;
  public int JJTENCABEZAD = 3;
  public int JJTENCABEZADO_VAL = 4;
  public int JJTLISTA_UNIDADES = 5;
  public int JJTUNIDAD = 6;
  public int JJTOBTENERVALORUNIDAD = 7;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "TAG",
    "ENCABEZAD",
    "Encabezado_Val",
    "LISTA_UNIDADES",
    "unidad",
    "obtenerValorUnidad",
  };
}
/* JavaCC - OriginalChecksum=faaed967f485ce011c51ebb10f923e42 (do not edit this line) */
